     @startuml

     actor "User" as user

     node "PHP Login Management" {
        node "Model" as model
        node "Domain" as domain
        node "Controller" as controller
        node "View" as view
        node "Service" as service
        node "Repository" as repository
     }

     database "MySQL" as mysql

     user --> controller : 1
     controller --> model : 2
     controller --> service : 3
     service --> repository : 4
     repository --> domain : 5
     repository --> mysql : 6
     controller --> view : 7
     controller --> user : 8


     @enduml